name: Unit Test Check
on:
    pull_request:
        branches:
            - master

jobs:
    unit-test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run unit-test composite action
              uses: Pulsifi/github-template/unit-test@master
              with:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Test Report
              continue-on-error: true
              uses: dorny/test-reporter@v1
              if: ${{ always() }}
              with:
                  name: test-results
                  path: coverage/jest-junit.xml
                  reporter: jest-junit
